### ISSUE TITLE
Other resources

### ISSUE THREAD

**Issue by A1rPun** [czyys/dustforceguide#1]
Very well written guide, I haven't finished it yet tho ;)

I would like to suggest some more resources you can add. The console version didn't get much attention but there are trophy guides for the playstation 3 and VITA version, one is written by me and the other one by a friend of mine: ThanatosNinja2.

- https://www.playstationtrophies.org/game/dustforce/guide/
- https://psnprofiles.com/guide/2666-dustforce-trophy-guide

Msg555 has made some cool things for dustforce, some of the stuff he made:
- https://github.com/msg555/dustmaker
- https://github.com/msg555/DustforceAutosplitter

**Comment by czyys** [comment]
I'm glad you like it!

Thank you for the suggestions but they're all out of scope of this project:

- The guide is made specifically for the DX version, which is only available for PC Windows, Linux and Mac OS X. I'm going to mention it.

- Dustmaker doesn't have any features for getting better at the game and the autosplitter is only useful for speedruns, which this guide isn't going to mention.

**Comment by A1rPun** [comment]
Thanks for the information! I understand it is out of scope.
